### ISSUE TITLE
Hint in readme about different google addresses

### ISSUE THREAD

**Issue by habegage** [attio/google-ad-fixer#4]
Hi! :)

It took me a while to realize that the matcher in the manifest matched only google.com and not other localized sites like google.de, which I'm using - while it's easy to adjust, can you maybe add a little hint about that in the readme, so it's more obvious? Thanks! And thanks for the plugin, this helps a lot :)

**Comment by nicolassharp** [comment]
Yes, you're right. 

A PR just went in: https://github.com/attio/google-ad-fixer/pull/3
